# Generated by Django 4.2.7 on 2023-11-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('category_sort_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['category_sort_id'],
            },
        ),
    ]
