# Generated by Django 4.2.7 on 2023-11-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistrooapp_admin', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menuu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_date', models.DateField()),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['menu_date', 'category_name', 'description'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
