# Generated by Django 4.2.7 on 2023-11-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistrooapp_admin', '0003_menuu_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuu',
            name='price_full',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='menuu',
            name='price_half',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
