# Generated by Django 4.2.7 on 2023-11-02 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bistrooapp_admin', '0004_menuu_price_full_menuu_price_half'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuu',
            options={'ordering': ['-menu_date', 'category_name', 'description']},
        ),
        migrations.AlterField(
            model_name='menuu',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bistrooapp_admin.category'),
        ),
        migrations.AlterField(
            model_name='menuu',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
