# Generated by Django 4.2.7 on 2023-11-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistrooapp_admin', '0005_alter_menuu_options_alter_menuu_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuu',
            name='price_full',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='menuu',
            name='price_half',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
